theme: jekyll-theme-slate
title: Welome to Spencee1315's [hompage](https://github.com/spencee1315/https-spencee1315.github.io-reading-notes-/edit/gh-pages/_index.md/)!
description: A reflection, on "How you can benefit from a growth mindset" by STEVE HAFFENDEN. Explaining Growth Mindset in my own words.
